package net.eclipce.somnium.core.tag;

import net.eclipce.somnium.core.ability.AbilityType;
import net.eclipce.somnium.core.registry.SomniumRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;

/**
 * Built-in {@link TagKey} constants for the ability type registry.
 *
 * <p>Tags are the data-driven way to categorize abilities. They replace
 * hard-coded groupings with JSON files that datapacks can modify. Somnium
 * defines several standard tags here; addon mods can create their own
 * and add to these via {@code SomniumAbilityTagsProvider} during datagen.</p>
 *
 * <h3>Tag file locations</h3>
 * <p>Tags for the ability type registry live at:</p>
 * <pre>data/&lt;namespace&gt;/tags/somnium/ability_types/&lt;tagpath&gt;.json</pre>
 * <p>For example, the transformation tag resolves to:</p>
 * <pre>data/somnium/tags/somnium/ability_types/transformation.json</pre>
 *
 * <h3>Usage at runtime</h3>
 * <pre>{@code
 * // Check if an ability is a transformation
 * boolean isTrans = SomniumRegistries.isAbilityInTag(
 *     myAbility, SomniumAbilityTags.TRANSFORMATION
 * );
 *
 * // Check if two abilities conflict
 * boolean conflict = SomniumRegistries.doAbilitiesConflict(abilityA, abilityB);
 * }</pre>
 *
 * <h3>Creating custom tags</h3>
 * <p>Addon mods can define their own tags for their conflict categories:</p>
 * <pre>{@code
 * public class ModAbilityTags {
 *     public static final TagKey<AbilityType> FLIGHT =
 *         SomniumAbilityTags.create(new ResourceLocation("mymod", "flight"));
 *     public static final TagKey<AbilityType> FIRE =
 *         SomniumAbilityTags.create(new ResourceLocation("mymod", "fire"));
 * }
 * }</pre>
 *
 * @see SomniumRegistries#isAbilityInTag(AbilityType, TagKey)
 * @see SomniumRegistries#doAbilitiesConflict(AbilityType, AbilityType)
 */
public final class SomniumAbilityTags {

    // ═══════════════════════════════════════════════════════════════════
    //  Built-in conflict/category tags
    // ═══════════════════════════════════════════════════════════════════

    /**
     * Tag for all transformation abilities. All {@code TransformationAbilityType}
     * instances should be in this tag. Ensures mutual exclusivity — only one
     * transformation can be active at a time.
     *
     * <p>This tag is automatically generated by the datagen provider for any
     * ability that declares it via
     * {@link net.eclipce.somnium.core.ability.AbilityType.Properties#conflictTag}.</p>
     */
    public static final TagKey<AbilityType> TRANSFORMATION = create("transformation");

    /**
     * Tag for movement-related abilities (flight, speed boost, teleport, dash).
     * Addon devs can use this to flag potential movement conflicts.
     */
    public static final TagKey<AbilityType> MOVEMENT = create("movement");

    /**
     * Tag for defensive abilities (shields, damage reduction, invulnerability).
     */
    public static final TagKey<AbilityType> DEFENSIVE = create("defensive");

    /**
     * Tag for offensive abilities (damage boosts, projectiles, AoE attacks).
     */
    public static final TagKey<AbilityType> OFFENSIVE = create("offensive");

    // ═══════════════════════════════════════════════════════════════════
    //  Factory methods
    // ═══════════════════════════════════════════════════════════════════

    /**
     * Creates a tag key under the {@code somnium} namespace.
     * Used internally for Somnium's built-in tags.
     *
     * @param path the tag path (e.g., "transformation")
     * @return the tag key
     */
    private static TagKey<AbilityType> create(String path) {
        return SomniumRegistries.ABILITY_TYPES.createTagKey(path);
    }

    /**
     * Creates a tag key for the ability type registry with a custom
     * {@link ResourceLocation}. Addon mods use this to define their
     * own ability tags.
     *
     * @param id the full ResourceLocation for the tag
     *           (e.g., {@code new ResourceLocation("mymod", "fire")})
     * @return the tag key
     */
    public static TagKey<AbilityType> create(ResourceLocation id) {
        return SomniumRegistries.ABILITY_TYPES.createTagKey(id);
    }

    // Private constructor — utility class
    private SomniumAbilityTags() {}
}